#!/usr/bin/env bash
# Install and configure HAproxy on lb-01 server

# Update the package list
sudo apt-get update

# Install HAProxy
sudo apt-get -y install haproxy

# Domain name and configuration paths
DOMAIN_NAME='nicky-mane.tech'  # Replace with your student ID
INIT_FILE='/etc/default/haproxy'
CONFIG_FILE='/etc/haproxy/haproxy.cfg'

# HAProxy configuration
HAPROXY_LB_CONFIG="
#--$DOMAIN_NAME-params-begin--
global
    log /dev/log    local0
    log /dev/log    local1 notice
    maxconn 2000
    user haproxy
    group haproxy

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

backend $DOMAIN_NAME-backend
    balance roundrobin
    mode http
    server 281042-web-01 18.235.255.120:80 check
    server 281042-web-02 52.201.157.77:80 check

frontend $DOMAIN_NAME-frontend
    bind *:80
    mode http
    default_backend $DOMAIN_NAME-backend

#--$DOMAIN_NAME-params-end--
"

# Ensure the initialization file exists
[ -f "$INIT_FILE" ] || sudo touch "$INIT_FILE"

# Ensure the HAProxy configuration file exists
[ -f "$CONFIG_FILE" ] || sudo touch "$CONFIG_FILE"

# Check if the HAProxy configuration section exists and update it
CONFIG_WORDS=$(grep -Eco "$DOMAIN_NAME-backend" < $CONFIG_FILE)

# Check if HAProxy is enabled and enable it if necessary
if [ "$(grep -Eco '^ENABLED=[01]$' < $INIT_FILE)" -gt 0 ]; then
    sudo sed -i 's/^ENABLED=0$/ENABLED=1/' "$INIT_FILE"
else
    echo 'ENABLED=1' | sudo tee $INIT_FILE
fi

# Update HAProxy configuration
if [ "$CONFIG_WORDS" -eq 0 ]; then
    echo -e "$HAPROXY_LB_CONFIG" | sudo tee $CONFIG_FILE
else
    start_tkn="#--$DOMAIN_NAME-params-begin--"
    end_tkn="#--$DOMAIN_NAME-params-end--"
    a=$(grep -onE "$start_tkn" < "$CONFIG_FILE" | cut -d : -f1)
    b=$(grep -onE "$end_tkn" < "$CONFIG_FILE" | cut -d : -f1)
    a=$((a - 1))
    b=$((b + 1))
    sudo sed -i "$a,$b"d "$CONFIG_FILE"
    echo -en "$HAPROXY_LB_CONFIG" | sudo tee -a $CONFIG_FILE
fi

# Start or restart HAProxy
if [ "$(pgrep -c haproxy)" -le 0 ]; then
    sudo service haproxy start
else
    sudo service haproxy restart
fi

# Enable HAProxy to start on boot
sudo systemctl enable haproxy
