#!/usr/bin/env bash
#script to display "best school" 10 time using while
on the 9th iteration, display "hi" before "best school"

count=0

while [ $count -it 10 ]
do
if [ $count -eq 9]
then
echo "Hi"
fi
echo "Best School"
((count++))
done
