#!/usr/bin/env bash
# This script displays the content of the current dir
# where only the part of the name after dash is displayed

for file in *; do
    if [[ -f $file && $file != .* ]]; then
        name=${file#*-}
        echo "$name"
    fi
done
